public abstract class PrestamoLibroAbstracta {
    
    protected String categoria;
    protected String titulo;
    protected String cant;
    protected String cant_a1_p;
    protected String cant_a2_p;
    protected String cant_a3_p;
    protected String cant_cf1_p;
    protected String cant_cf2_p;
    protected String cant_cf3_p;
    protected String cant_ch1_p;
    protected String cant_ch2_p;
    protected String cant_ch3_p;
    protected String cant_g1_p;
    protected String cant_g2_p;
    protected String cant_g3_p;
    protected String cant_pl1_p;
    protected String cant_pl2_p;
    protected String cant_pl3_p;
    protected String cant_pa1_p;
    protected String cant_pa2_p;
    protected String cant_pa3_p;
    protected String cant_f1_p;
    protected String cant_f2_p;
    protected String cant_f3_p;

    public abstract String getCategoria();
    public abstract void setCategoria(String categoria);
    public abstract String getTitulo();
    public abstract void setTitulo(String titulo);
    public abstract String getCant();
    public abstract void setCant(String cant);
    public abstract String getCant_a1_p();
    public abstract void setCant_a1_p(String cant_a1_p);
    public abstract String getCant_a2_p();
    public abstract void setCant_a2_p(String cant_a2_p);
    public abstract String getCant_a3_p();
    public abstract void setCant_a3_p(String cant_a3_p);
    public abstract String getCant_cf1_p();
    public abstract void setCant_cf1_p(String cant_cf1_p);
    public abstract String getCant_cf2_p();
    public abstract void setCant_cf2_p(String cant_cf2_p);
    public abstract String getCant_cf3_p();
    public abstract void setCant_cf3_p(String cant_cf3_p);
    public abstract String getCant_ch1_p();
    public abstract void setCant_ch1_p(String cant_ch1_p);
    public abstract String getCant_ch2_p();
    public abstract void setCant_ch2_p(String cant_ch2_p);
    public abstract String getCant_ch3_p();
    public abstract void setCant_ch3_p(String cant_ch3_p);
    public abstract String getCant_g1_p();
    public abstract void setCant_g1_p(String cant_g1_p);
    public abstract String getCant_g2_p();
    public abstract void setCant_g2_p(String cant_g2_p);
    public abstract String getCant_g3_p();
    public abstract void setCant_g3_p(String cant_g3_p);
    public abstract String getCant_pl1_p();
    public abstract void setCant_pl1_p(String cant_pl1_p);
    public abstract String getCant_pl2_p();
    public abstract void setCant_pl2_p(String cant_pl2_p);
    public abstract String getCant_pl3_p();
    public abstract void setCant_pl3_p(String cant_pl3_p);
    public abstract String getCant_pa1_p();
    public abstract void setCant_pa1_p(String cant_pa1_p);
    public abstract String getCant_pa2_p();
    public abstract void setCant_pa2_p(String cant_pa2_p);
    public abstract String getCant_pa3_p();
    public abstract void setCant_pa3_p(String cant_pa3_p);
    public abstract String getCant_f1_p();
    public abstract void setCant_f1_p(String cant_f1_p);
    public abstract String getCant_f2_p();
    public abstract void setCant_f2_p(String cant_f2_p);
    public abstract String getCant_f3_p();
    public abstract void setCant_f3_p(String cant_f3_p);
    
}
