public interface VentaLibroInterfaz {
    
    public String getCategoria();
    public void setCategoria(String categoria);
    public String getTitulo();
    public void setTitulo(String titulo);
    public String getCant();
    public void setCant(String cant);
    public String getCant_a1_v();
    public void setCant_a1_v(String cant_a1_v);
    public String getCant_a2_v();
    public void setCant_a2_v(String cant_a2_v);
    public String getCant_a3_v();
    public void setCant_a3_v(String cant_a3_v);
    public String getCant_cf1_v();
    public void setCant_cf1_v(String cant_cf1_v);
    public String getCant_cf2_v();
    public void setCant_cf2_v(String cant_cf2_v);
    public String getCant_cf3_v();
    public void setCant_cf3_v(String cant_cf3_v);
    public String getCant_ch1_v();
    public void setCant_ch1_v(String cant_ch1_v);
    public String getCant_ch2_v();
    public void setCant_ch2_v(String cant_ch2_v);
    public String getCant_ch3_v();
    public void setCant_ch3_v(String cant_ch3_v);
    public String getCant_g1_v();
    public void setCant_g1_v(String cant_g1_v);
    public String getCant_g2_v();
    public void setCant_g2_v(String cant_g2_v);
    public String getCant_g3_v();
    public void setCant_g3_v(String cant_g3_v);
    public String getCant_pl1_v();
    public void setCant_pl1_v(String cant_pl1_v);
    public String getCant_pl2_v();
    public void setCant_pl2_v(String cant_pl2_v);
    public String getCant_pl3_v();
    public void setCant_pl3_v(String cant_pl3_v);
    public String getCant_pa1_v();
    public void setCant_pa1_v(String cant_pa1_v);
    public String getCant_pa2_v();
    public void setCant_pa2_v(String cant_pa2_v);
    public String getCant_pa3_v();
    public void setCant_pa3_v(String cant_pa3_v);
    public String getCant_f1_v();
    public void setCant_f1_v(String cant_f1_v);
    public String getCant_f2_v();
    public void setCant_f2_v(String cant_f2_v);
    public String getCant_f3_v();
    public void setCant_f3_v(String cant_f3_v);
}
